name: Schedule Continuous Increment

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours

permissions:
  contents: write

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
      # Trigger the Continuous Increment workflow
      - name: Trigger Continuous Increment
        uses: actions/github-script@v6
        with:
          script: |
            const fetch = require('node-fetch');
            const response = await fetch('https://api.github.com/repos/Titan637/RAGNAROK/actions/workflows/continuous-increment.yml/dispatches', {
              method: 'POST',
              headers: {
                Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
                Accept: 'application/vnd.github.everest-preview+json',
              },
              body: JSON.stringify({
                ref: 'main'
              }),
            });
            console.log(`Triggered workflow with response: ${response.status}`);
