name: Incremental Workflow Every 12 Minutes

on:
  workflow_dispatch:  # Manual trigger to start the loop
  push:  # Automatically triggers when the previous workflow commits
    branches:
      - main
  schedule:
    - cron: '*/12 * * * *'  # Run every 12 minutes

permissions:
  contents: write  # Allow GitHub Actions to push changes

jobs:
  append_increment:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Append incremental numbers to hello.txt and commit changes
      - name: Increment and commit
        run: |
          # Get the last number from hello.txt or start with 0 if the file doesn't exist
          LAST_NUMBER=$(tail -n 1 hello.txt 2>/dev/null || echo "0")
          if [[ ! $LAST_NUMBER =~ ^[0-9]+$ ]]; then
            LAST_NUMBER=0
          fi

          # Increment the number
          NEW_NUMBER=$((LAST_NUMBER + 1))

          # Append the new number to hello.txt
          echo $NEW_NUMBER >> hello.txt

          # Commit and push the change
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add hello.txt
          git commit -m "Append number $NEW_NUMBER"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Titan637/RAGNAROK.git
